name: Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5.1.1
      with:
        python-version: "3.12"
        cache: pip
    - name: Install setuptools
      run: pip install setuptools
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"
    - name: Build gogopython
      run: CGO_ENABLED=0 go build
    - name: Run example.go
      run: go run example/example.go
